# Generated by Django 5.1.4 on 2024-12-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-date_of_publication']},
        ),
    ]
